spring.application.name=books-service

spring.datasource.url=jdbc:oracle:thin:@x4jr6t1j9re665hr_high?TNS_ADMIN=src/main/resources/Wallet_X4JR6T1J9RE665HR
spring.datasource.username=LAB_USERS
spring.datasource.password=P4rM3d-Users\#2025!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.initializationFailTimeout=0

server.port=8081
